# NumPy

In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,4, 8,10])
print(arr)

[ 1  2  4  8 10]


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
matrix = np.array([[1,2,3], [4,5,7], [9,10,15]])
print(matrix)

[[ 1  2  3]
 [ 4  5  7]
 [ 9 10 15]]


In [10]:
arr_2 = np.array([1,2,4, 8,10])
arr_1 = np.array([2,24,5, 18,100])

print(arr_1 + arr_2)
print(arr_1 - arr_2)
print(arr_1 * arr_2)
print(arr_1 / arr_2)
print(arr_1 % arr_2)

[  3  26   9  26 110]
[ 1 22  1 10 90]
[   2   48   20  144 1000]
[ 2.   12.    1.25  2.25 10.  ]
[0 0 1 2 0]


In [13]:
list_1 = [1,2,4, 8,10]
list_2 = [1,2,4, 8,10]

print(list_1 + list_2)

[1, 2, 4, 8, 10, 1, 2, 4, 8, 10]


In [15]:
arr_3 = np.array([4, 9, 36, 100, 625])

print(np.sqrt(arr_3))

[ 2.  3.  6. 10. 25.]


In [21]:
matrix_1 = np.array([1,2,3,4,10, 15, 20, 100])

reshape_matrix_1 = matrix_1.reshape(2,4)

print(matrix_1)
print(reshape_matrix_1)

[  1   2   3   4  10  15  20 100]
[[  1   2   3   4]
 [ 10  15  20 100]]


In [24]:
matrix_2 = np.array([[1,2,3, 6], [4,5,7, 6], [10, 15, 20, 200]])

transpose_matrix_2 = matrix_2.T

print(matrix_2)
print(transpose_matrix_2)

[[  1   2   3   6]
 [  4   5   7   6]
 [ 10  15  20 200]]
[[  1   4  10]
 [  2   5  15]
 [  3   7  20]
 [  6   6 200]]


In [27]:
matrix_3 = np.array([1,2,3,4,5,6])

print(np.sum(matrix_3))

print(np.mean(matrix_3))

print(np.max(matrix_3))
print(np.min(matrix_3))

21
3.5
6
1


In [47]:
matrix_4 = np.array([[1,2,3, 6], [4,5,7, 6], [10, 15, 20, 200]])

# print(matrix_4)
# print(matrix_4[2,3])

# print(matrix_3[:1])
print(matrix_4[:2, 0])
print(matrix_4[-2])

[1 4]
[4 5 7 6]
